config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'password_resets/edit'
  get 'password_resets/new'
  get 'sessions/new'
  get 'users/new'

  get    'home'    => 'users#show'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :weight_entries,      only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made with &lt;3 by <a href="http://www.kylebeede.com/">Kyle Beede</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="mast-head nav navbar-nav">
	<div class="mast-head__container container">
		<nav class="mast-head__nav">
			<ul class="nav-list">
				<% if @user && logged_in? %>
					<li class="nav-list__item header-account-menu">
						<a class="header-nav-link"><%= @user.name %></a>
						<div class="sub-nav">
							<ul>
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li><%= link_to "Sign out", logout_path, method: "delete", class: "sign-in button-link" %></li>
							</ul>
						</div>
					</li>
				<% else %>
				  <li class="nav-list__item"><%= link_to "Sign in", login_path, class: "sign-in button-link" %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>
<script>
	$(document).ready(function(){
		var navLink = document.querySelector( ".header-account-menu .header-nav-link" );
		var subNav = document.querySelector( ".header-account-menu .sub-nav" );

		if (navLink) {
			navLink.addEventListener( "click", function(){
				$(subNav).toggleClass("active");
			});
		}
	});
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="weight-tracker">
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
	  <div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>

	<%= yield %>

	<%= render 'layouts/footer' %>

	<%= debug(params) if Rails.env.development? %>

</body>
</html>